# Generated by Django 4.0.5 on 2022-07-05 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=21, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=21, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'Coordinates',
                'verbose_name_plural': 'Coordinates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, verbose_name='Title')),
                ('first', models.CharField(max_length=50, verbose_name='First')),
                ('last', models.CharField(max_length=50, verbose_name='Last')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.URLField(max_length=255, verbose_name='Large')),
                ('medium', models.URLField(max_length=255, verbose_name='Medium')),
                ('thumbnail', models.URLField(max_length=255, verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimezoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.CharField(max_length=8, verbose_name='Offset')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Time Zones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15, verbose_name='Region')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('postcode', models.IntegerField(verbose_name='Postcode')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_model', to='customers.coordinatesmodel')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_model', to='customers.timezonemodel')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=50, verbose_name='Type')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('birthday', models.CharField(max_length=50, verbose_name='Birthday')),
                ('registered', models.CharField(max_length=50, verbose_name='Registered')),
                ('telephone_numbers', models.JSONField(default=list, verbose_name='Telephone Numbers')),
                ('mobile_numbers', models.JSONField(default=list, verbose_name='Mobile Numbers')),
                ('nationality', models.CharField(default='BR', max_length=2, verbose_name='Nationality')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_model', to='customers.locationmodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_model', to='customers.namemodel')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_model', to='customers.picturemodel')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['id'],
            },
        ),
    ]
